#pragma once
#include "main.h"
#include "321Hlib/auton.h"
#include "321Hlib/functions.h"
#include "321Hlib/robotConfig.h"
#include "321Hlib/SystemControl/systemControl.h"
#include "321Hlib/SystemControl/intakeTask.h"
#include "321Hlib/SystemControl/catapultTask.h"
#include "321Hlib/odometry/odometry.h"
